version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.web
    restart: always
    command: bash -c "gunicorn -w 2 --bind 0.0.0.0:8080 run:app"
    env_file:
      - ./docker/web/.env-web
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo

  mongo:
    build:
      context: ./docker/mongo/
      dockerfile: Dockerfile.mongo
    restart: always
    env_file:
      - ./docker/mongo/.env-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ./docker/mongo-express/.env-express
    depends_on:
      - mongo

  redis:
    image: redis
    restart: always

  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile.worker
    command: bash -c "celery -A api_service.celery_worker:app worker --beat --loglevel=info"
    restart: always
    env_file:
      - ./docker/worker/.env-worker
    depends_on:
      - redis
      - web
