version: "3.9"
services:
  watchdog:
    build:
      context: .
      dockerfile: ./docker/watchdog/Dockerfile.watchdog
    # TODO: removw init_db.py
    command: bash -c "python init_db.py && python watchdog.py"
    restart: always
    env_file:
      - ./docker/watchdog/.env-watchdog
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./docker/mongo/.env-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ./docker/mongo-express/.env-express
    depends_on:
      - mongo