FROM python:3.7-slim-buster

RUN useradd -d /home/web -m web
WORKDIR /home/web

# This prevents Python from writing out pyc files
ENV PYTHONDONTWRITEBYTECODE 1
# This keeps Python from buffering stdin/stdout
ENV PYTHONUNBUFFERED 1

COPY --chown=web:web requirements.txt .

# install dependencies and gunicorn
RUN pip install -r requirements.txt \
	&& pip install gunicorn \
	&& apt-get update && apt-get install -y curl && apt-get clean

# Copy project's files as web user
COPY --chown=web:web . .

USER web

EXPOSE 8080

# Create db and add some dummy data
# RUN python init_db.py